### PR TITLE
Update semiautomaticclassificationplugin_fr.ts

### PR DESCRIPTION
**Pull request by GITHUBAntoineDENIS**
Some additional corrections of the french interface

### CODE REVIEW

**Comment by semiautomaticgit** [comment]
Thank you very much for your work!

**Comment by GITHUBAntoineDENIS** [comment]
You're very welcome. It's my pleasure.
Thank you to you for your very nice SCP plugin. 
Best regards,
Antoine 

----- Mail original -----
De: "Luca Congedo" <notifications@github.com>
À: "semiautomaticgit/SemiAutomaticClassificationPlugin" <SemiAutomaticClassificationPlugin@noreply.github.com>
Cc: "Antoine DENIS" <Antoine.DENIS@uliege.be>, "Author" <author@noreply.github.com>
Envoyé: Mardi 31 Mars 2020 12:33:06
Objet: Re: [semiautomaticgit/SemiAutomaticClassificationPlugin] Update semiautomaticclassificationplugin_fr.ts (#93)

Thank you very much for your work!

**Comment by GITHUBAntoineDENIS** [comment]
By the way, do you have an idea of when the new version of SCP including these corrections will be available?
I also plan to check the french translation of the 3 remaining menus preprocess, process and postprocess that I did not yet checked.


----- Mail original -----
De: "Luca Congedo" <notifications@github.com>
À: "semiautomaticgit/SemiAutomaticClassificationPlugin" <SemiAutomaticClassificationPlugin@noreply.github.com>
Cc: "Antoine DENIS" <Antoine.DENIS@uliege.be>, "Author" <author@noreply.github.com>
Envoyé: Mardi 31 Mars 2020 12:33:06
Objet: Re: [semiautomaticgit/SemiAutomaticClassificationPlugin] Update semiautomaticclassificationplugin_fr.ts (#93)

Thank you very much for your work!

**Comment by semiautomaticgit** [comment]
I can update the plugin as soon as you confirm that you have completed your corrections.

**Comment by GITHUBAntoineDENIS** [comment]
Great! So I will tell you when I am finished with these corrections... maybe in one week...

----- Mail original -----
De: "Luca Congedo" <notifications@github.com>
À: "semiautomaticgit/SemiAutomaticClassificationPlugin" <SemiAutomaticClassificationPlugin@noreply.github.com>
Cc: "Antoine DENIS" <Antoine.DENIS@uliege.be>, "Author" <author@noreply.github.com>
Envoyé: Mardi 31 Mars 2020 13:15:04
Objet: Re: [semiautomaticgit/SemiAutomaticClassificationPlugin] Update semiautomaticclassificationplugin_fr.ts (#93)

I can update the plugin as soon as you confirm that you have completed your corrections.

**Comment by GITHUBAntoineDENIS** [comment]
Hello Luca,
I made 4 additional pull request
for #95 see my comments... I have a doubt for one correction

Also you may consider the issues 88 94 99 and 100
and implement the corrections by yourself as I was not able to do them.

I am now finished with the corrections I wanted to bring. So for me you can update the plugin.

Best regards,
Antoine 

----- Mail original -----
De: "Luca Congedo" <notifications@github.com>
À: "semiautomaticgit/SemiAutomaticClassificationPlugin" <SemiAutomaticClassificationPlugin@noreply.github.com>
Cc: "Antoine DENIS" <Antoine.DENIS@uliege.be>, "Author" <author@noreply.github.com>
Envoyé: Mardi 31 Mars 2020 13:15:04
Objet: Re: [semiautomaticgit/SemiAutomaticClassificationPlugin] Update semiautomaticclassificationplugin_fr.ts (#93)

I can update the plugin as soon as you confirm that you have completed your corrections.

**Pull request merged**
